#!/bin/bash
# only run if this appears to be the main gear
if [ -a ${OPENSHIFT_DATA_DIR}main_gear ] ; then
  echo 'starting clockwork'
  cd $OPENSHIFT_REPO_DIR
  cmd="bundle exec clockworkd --pid-dir=${OPENSHIFT_DATA_DIR} --clock=clock.rb --log --log-dir=${OPENSHIFT_RUBY_LOG_DIR}"

  echo $cmd
  ${cmd} stop
  ${cmd} start
fi